name: Deploy JS Client Docs

on:
  workflow_dispatch:

env:
  CACHE: true

jobs:
  deploy_js:
    name: JS client / Deploy documentation
    runs-on: ubuntu-latest
    environment:
      name: js-client-documentation
      url: https://mpl-hydra-js-docs-lorismatic-metaplex.vercel.app/
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./clients/js
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
